# Generated by Django 5.2.6 on 2026-06-22 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_event_legacy_fields'),
        ('venues', '0003_alter_venuebookingrequest_requester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('event_deactivated', 'Event Deactivated'), ('event_deleted', 'Event Deleted'), ('venue_deactivated', 'Venue Deactivated'), ('venue_deleted', 'Venue Deleted'), ('other', 'Other')], default='other', max_length=30)),
                ('reason', models.CharField(choices=[('late_payment', 'Late Payment'), ('technical_difficulties', 'Technical Difficulties'), ('policy_violation', 'Policy Violation'), ('security_concern', 'Security Concern'), ('fraud', 'Fraud'), ('duplicate', 'Duplicate Account'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to='events.event')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to='venues.venue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
