# Generated by Django 5.2.6 on 2026-06-29 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='reviews.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_deactivated', 'Event Deactivated'), ('event_deleted', 'Event Deleted'), ('venue_deactivated', 'Venue Deactivated'), ('venue_deleted', 'Venue Deleted'), ('new_comment', 'New Comment'), ('comment_reply', 'Comment Reply'), ('new_review', 'New Review'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
