# Generated by Django 5.2.6 on 2026-06-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_deactivated', 'Event Deactivated'), ('event_deleted', 'Event Deleted'), ('venue_deactivated', 'Venue Deactivated'), ('venue_deleted', 'Venue Deleted'), ('new_comment', 'New Comment'), ('comment_reply', 'Comment Reply'), ('new_review', 'New Review'), ('new_booking', 'New Booking'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
